
name: is_dark

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        ruby:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
          - head

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Change ImageMagick policy to allow pdf->png conversion.
        run: sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml

      - name: Install Ghostscript
        run: sudo apt-get install -y ghostscript
      
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Display Ruby version
        run: ruby -v

      - name: Test
        run: bundle exec rspec

      - name: Run Rubocop linter
        run: bundle exec rubocop
