name: is_dark

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        ruby:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
          - head

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Display Ruby version
        run: ruby -v

      - name: Test
        run: bundle exec rspec
